### ISSUE TITLE
BB [master] - Few issues while testing bluebanquise/bluebanquise

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#580] opened 2021-07-14 16:58 UTC
Hi @oxedions 

Noticed the following issues (mix of Bluebanquise and Community issues) ... for screening.

Environment:

- Vagrant (latest)
![image](https://user-images.githubusercontent.com/5890515/125662313-2e30bfbe-02c0-4e04-ab10-68ec16fc259f.png)

- BB/Community (clone of master of bluebanquise/bluebanquise & strus_38/community)
- CentOS Linux release 8.4.2105

Issues:

-  Centos-extras seems Centos-Linux-Extras ... not sure from where it comes!

![BB-BUg1](https://user-images.githubusercontent.com/5890515/125661172-832fcd64-1d41-467b-95be-609a5be7134d.PNG)

Workaround: `ansible-playbook /etc/bluebanquise/playbooks/managements.yml --limit management1 -erepositories_client_disable_distro_repos=False`

-  Tasks 'name: ' should not contain variables when  with_items is used - they are not interpreted (1 exemple)  

![BB-BUg2](https://user-images.githubusercontent.com/5890515/125661466-a8d2c214-fea1-4ca7-8636-2550e82e4065.PNG)

- Timezone issue when selinux is enabled

![BB-BUg3](https://user-images.githubusercontent.com/5890515/125661573-23eb4b72-93f1-49f5-a8a7-ad8094159cdc.PNG)

Workaround running those commands:
![BB-BUg3-1](https://user-images.githubusercontent.com/5890515/125661587-deacc928-6029-4f7a-b0f8-fc04664fbfa9.PNG)

- Prometheus is not able to install the requirement: `dnf install freeipmi` by it-self.
Workaround: run this manually.

**Comment by btravouillon** [comment] 2021-07-17 19:39
Yeah the folks from CentOS renamed the repo files in 8.4 to be compliant with Stream. I guess their target is to ensure smooth migration from 8.4 to Stream by the end of this year.

**Comment by btravouillon** [comment] 2021-07-17 19:41
This one is already reported in #534 btw.

**Comment by johnnykeats** [comment] 2021-11-15 09:57
@strus38 
Could you provide more context about Chrony and Selinux? Not able to reproduce in VMs.

**Comment by ginomcevoy** [comment] 2021-12-01 18:24
Hello @johnnykeats , @strus38 ,
We have seen this issue before in our virtual environment to test BlueBanquise, I would say this issue is "vagrant only".
As a workaround we run "restorecon -Rv /etc" as part of the provisioning step. Here is an output example of vagrant up:

```
...

           default: Relabeled /etc/localtime from unconfined_u:object_r:etc_t:s0 to unconfined_u:object_r:locale_t:s0
           default: Relabeled /etc/sysconfig/network-scripts/ifcfg-eth1 from unconfined_u:object_r:user_tmp_t:s0 to unconfined_u:object_r:net_conf_t:s0
           default: Relabeled /etc/sysconfig/network-scripts/ifcfg-eth2 from unconfined_u:object_r:user_tmp_t:s0 to unconfined_u:object_r:net_conf_t:s0
```

The role runs well after this, and I have not reproduced outside of vagrant.

**Comment by oxedions** [comment] 2021-12-03 08:02
Dear @ginomcevoy
Thanks a lot for providing the solution 😊 
We can then close this issue, as it is not directly related to the stack.

**Closed by oxedions** 2021-12-03 08:02 UTC
