### ISSUE TITLE
[BUG] dns_server: reverse resolution not working for /22 network prefix

### ISSUE THREAD

**Issue by ginomcevoy** [bluebanquise/bluebanquise#682] opened 2022-03-02 17:11 UTC
This is relevant to the dns_server core role, currently it does not configure certain networks correctly and reverse resolution fails.

## Context

When defining a network with the /22 prefix (255.255.252.0 netmask), there can be nodes that are outside the "C-class range" of the network. For example, the 192.168.100.0/22 network can go up to 192.168.103.255, so it is possible to have a node with the 192.168.103.1 IP address inside that network.

The issue is that this node is not correctly configured in the dns_server role, namely the reverse resolution fails.

## Process

1. Define this network 192.168.100.0/22 in network.yml:
```
  ice1-2:
    subnet: 192.168.100.0
    prefix: 22
    netmask: 255.255.252.0
    broadcast: 192.168.103.255
    is_in_dns: true
```
2. Assign the interface of a node to 192.168.103.1 which is inside this ice1-2 network (login1 in this example). 

3. Run dns_server role, e.g.
```
ansible-playbook playbooks/managements.yml -t dns_server
```

## Expected result

Both forward and reverse DNS resolutions should work:
```
[root@management1 bluebanquise]# host login1
login1.tumulus.local has address 192.168.103.251

[root@management1 bluebanquise]# host 192.168.103.251
251.103.168.192.in-addr.arpa domain name pointer login1-ice1-2.tumulus.local.
251.103.168.192.in-addr.arpa domain name pointer login1.tumulus.local.
```
## Current result

DNS resolution works, but reverse resolution fails:
```
[root@management1 bluebanquise]# host login1
login1.smc.local has address 192.168.103.251
[root@management1 bluebanquise]# host 192.168.103.251
Host 251.103.168.192.in-addr.arpa not found: 5(REFUSED)
```
In fact, the reverse address has not been calculated properly (notice 192.168.100 instead of 192.168.103):
```
[root@management1 bluebanquise]# host 192.168.100.251
251.100.168.192.in-addr.arpa domain name pointer login1-ice1-2.tumulus.local.
251.100.168.192.in-addr.arpa domain name pointer login1.tumulus.local.
```
## Possible Fix

Not a DNS guru by any means, but I saw articles regarding this issue, and the recommendation (or standard practice?) is to "delegate multiple zones of the closest smaller size", e.g.

192.168.100.0/22 would be 100.168.192.in-addr.arpa, 101.168.192.in-addr.arpa, 102.168.192.in-addr.arpa, 103.168.192.in-addr.arpa. In that scenario, the node would be declared only in the fourth zone.

Maybe a simpler solution (to code in ansible!) exists. 

Edit: formatting

**Comment by neilmunday** [comment] 2022-03-02 21:38
Bug confirmed.

**Comment by neilmunday** [comment] 2022-03-03 23:34
Please see my suggest changes in pull request #683.

Test ouput:

```
wolf0:~ # host 192.168.103.1
1.103.168.192.in-addr.arpa domain name pointer wolf1-ice1-2.wolf.home.mundayweb.com.
wolf0:~ #
wolf0:~ # host wolf1-ice1-2.wolf.home.mundayweb.com
wolf1-ice1-2.wolf.home.mundayweb.com has address 192.168.103.1
```

**Comment by ginomcevoy** [comment] 2022-03-11 16:28
Hello @neilmunday ,

Sorry for the delay. I have just tested this somewhat extensively for the /22 and /16 networks, and everything works.

There are now multiple reverse zones created, e..g. 192.168.100.rr.zone, 192.168.101.rr.zone, 192.168.102.rr.zone, 192.168.103.rr.zone, as needed (only if there are hosts in these ranges).

This looks OK to me, thanks!

**Comment by neilmunday** [comment] 2022-03-11 17:56
@ginomcevoy glad to hear it works for you :-)

**Comment by oxedions** [comment] 2022-04-22 11:02
I am closing issue now, since it was solved 😊

**Closed by oxedions** 2022-04-22 11:02 UTC
Labels: bug
